server:
  port: 9998
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hxy
    username: root
    password: root
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=10,expireAfterWrite=10s
    cache-names: slow-computing-cache
management:
  endpoints:
    web:
      exposure:
        include: '*'
