/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hxy.recipe.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2023-01-16")
public class BigObject implements org.apache.thrift.TBase<BigObject, BigObject._Fields>, java.io.Serializable, Cloneable, Comparable<BigObject> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BigObject");

  private static final org.apache.thrift.protocol.TField A_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("aList", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BigObjectStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BigObjectTupleSchemeFactory());
  }

  public List<A> aList; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    A_LIST((short)1, "aList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // A_LIST
          return A_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.A_LIST};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.A_LIST, new org.apache.thrift.meta_data.FieldMetaData("aList", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, A.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BigObject.class, metaDataMap);
  }

  public BigObject() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BigObject(BigObject other) {
    if (other.isSetAList()) {
      List<A> __this__aList = new ArrayList<A>(other.aList.size());
      for (A other_element : other.aList) {
        __this__aList.add(new A(other_element));
      }
      this.aList = __this__aList;
    }
  }

  public BigObject deepCopy() {
    return new BigObject(this);
  }

  @Override
  public void clear() {
    this.aList = null;
  }

  public int getAListSize() {
    return (this.aList == null) ? 0 : this.aList.size();
  }

  public java.util.Iterator<A> getAListIterator() {
    return (this.aList == null) ? null : this.aList.iterator();
  }

  public void addToAList(A elem) {
    if (this.aList == null) {
      this.aList = new ArrayList<A>();
    }
    this.aList.add(elem);
  }

  public List<A> getAList() {
    return this.aList;
  }

  public BigObject setAList(List<A> aList) {
    this.aList = aList;
    return this;
  }

  public void unsetAList() {
    this.aList = null;
  }

  /** Returns true if field aList is set (has been assigned a value) and false otherwise */
  public boolean isSetAList() {
    return this.aList != null;
  }

  public void setAListIsSet(boolean value) {
    if (!value) {
      this.aList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case A_LIST:
      if (value == null) {
        unsetAList();
      } else {
        setAList((List<A>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case A_LIST:
      return getAList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case A_LIST:
      return isSetAList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BigObject)
      return this.equals((BigObject)that);
    return false;
  }

  public boolean equals(BigObject that) {
    if (that == null)
      return false;

    boolean this_present_aList = true && this.isSetAList();
    boolean that_present_aList = true && that.isSetAList();
    if (this_present_aList || that_present_aList) {
      if (!(this_present_aList && that_present_aList))
        return false;
      if (!this.aList.equals(that.aList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_aList = true && (isSetAList());
    list.add(present_aList);
    if (present_aList)
      list.add(aList);

    return list.hashCode();
  }

  @Override
  public int compareTo(BigObject other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetAList()).compareTo(other.isSetAList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.aList, other.aList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BigObject(");
    boolean first = true;

    if (isSetAList()) {
      sb.append("aList:");
      if (this.aList == null) {
        sb.append("null");
      } else {
        sb.append(this.aList);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BigObjectStandardSchemeFactory implements SchemeFactory {
    public BigObjectStandardScheme getScheme() {
      return new BigObjectStandardScheme();
    }
  }

  private static class BigObjectStandardScheme extends StandardScheme<BigObject> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BigObject struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // A_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.aList = new ArrayList<A>(_list8.size);
                A _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new A();
                  _elem9.read(iprot);
                  struct.aList.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setAListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BigObject struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.aList != null) {
        if (struct.isSetAList()) {
          oprot.writeFieldBegin(A_LIST_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.aList.size()));
            for (A _iter11 : struct.aList)
            {
              _iter11.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BigObjectTupleSchemeFactory implements SchemeFactory {
    public BigObjectTupleScheme getScheme() {
      return new BigObjectTupleScheme();
    }
  }

  private static class BigObjectTupleScheme extends TupleScheme<BigObject> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BigObject struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetAList()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetAList()) {
        {
          oprot.writeI32(struct.aList.size());
          for (A _iter12 : struct.aList)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BigObject struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.aList = new ArrayList<A>(_list13.size);
          A _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new A();
            _elem14.read(iprot);
            struct.aList.add(_elem14);
          }
        }
        struct.setAListIsSet(true);
      }
    }
  }

}

